/**
 * Exact 48 Run Upgrades Specification
 * Product Truth: company_sim_v1/product_final.md Section 16, 17, 18, 19
 *
 * 30 room-specific upgrades
 * 12 cross-room systems
 * 6 cursed upgrades
 * = 48 total
 */

import type { RoomId } from '../sim/types';

export type UpgradeCategory = 'room' | 'system' | 'cursed';
export type UpgradeRarity = 'common' | 'uncommon' | 'rare' | 'legendary' | 'cursed';

export interface UpgradeDefinition {
  id: string;
  name: string;
  category: UpgradeCategory;
  room?: RoomId;
  rarity: UpgradeRarity;
  costCu: number;
  complexity: number;
  effectId: string;
  description: string;
  mechanicNote: string;
}

export const ALL_UPGRADES: UpgradeDefinition[] = [
  // ==========================================
  // MARKETING (5)
  // ==========================================
  {
    id: 'mkt_trend_radar',
    name: 'Trend Radar',
    category: 'room',
    room: 'marketing',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'reveal_marketing_signal',
    description: 'Reveal one additional hidden Marketing signal. Manual combo grace +1 mistake.',
    mechanicNote: 'Makes Saturation signal visible and protects combo streak.',
  },
  {
    id: 'mkt_repurposer',
    name: 'Repurposer',
    category: 'room',
    room: 'marketing',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'marketing_repurpose_chance',
    description: '25% chance on correct RIGHT or UP to spawn a follow-up card worth 0.5 Demand.',
    mechanicNote: 'Increases marketing output without increasing cost.',
  },
  {
    id: 'mkt_channel_router',
    name: 'Channel Router',
    category: 'room',
    room: 'marketing',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0.5,
    effectId: 'marketing_agent_throughput_boost',
    description: 'Marketing Agent throughput +30%. Does not affect founder throughput.',
    mechanicNote: 'Boosts automated distribution velocity.',
  },
  {
    id: 'mkt_automation_license',
    name: 'Marketing Automation License',
    category: 'room',
    room: 'marketing',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'marketing_install_agent',
    description: 'Installs or upgrades the Marketing Agent line.',
    mechanicNote: 'Allows automation of card evaluation.',
  },
  {
    id: 'mkt_feedback_loop',
    name: 'Feedback Loop',
    category: 'room',
    room: 'marketing',
    rarity: 'rare',
    costCu: 3,
    complexity: 1.0,
    effectId: 'marketing_auto_pursue',
    description: 'After five agent-correct choices, next eligible card is automatically pursued.',
    mechanicNote: 'Carries low-quality risk if previous batch contained low quality.',
  },

  // ==========================================
  // PRODUCT (5)
  // ==========================================
  {
    id: 'prod_test_harness',
    name: 'Test Harness',
    category: 'room',
    room: 'product',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'product_auto_test',
    description: 'TEST automatically attaches to every second IMPLEMENTATION without manual drag.',
    mechanicNote: 'Speeds up verification pipeline.',
  },
  {
    id: 'prod_worktrees',
    name: 'Worktrees',
    category: 'room',
    room: 'product',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0.5,
    effectId: 'product_slot_expansion',
    description: 'Increase active Product request slots from 6 to 9 and allow dual piece spawns.',
    mechanicNote: 'High concurrency for fast builders.',
  },
  {
    id: 'prod_eval_gate',
    name: 'Eval Gate',
    category: 'room',
    room: 'product',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'product_rework_early_deploy',
    description: 'First early-deploy mistake every 20s converts into rework instead of Churn Threat.',
    mechanicNote: 'Safety net for risky early deployments.',
  },
  {
    id: 'prod_automation_license',
    name: 'Code Automation License',
    category: 'room',
    room: 'product',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'product_install_agent',
    description: 'Installs or upgrades the Product Agent line.',
    mechanicNote: 'Allows automated merging of request states.',
  },
  {
    id: 'prod_auto_deploy',
    name: 'Auto Deploy',
    category: 'room',
    room: 'product',
    rarity: 'rare',
    costCu: 3,
    complexity: 1.0,
    effectId: 'product_auto_deploy',
    description: 'VERIFIED requests deploy automatically after 1 second. No drag required.',
    mechanicNote: 'Eliminates final manual step in product pipeline.',
  },

  // ==========================================
  // MONETIZATION (5)
  // ==========================================
  {
    id: 'mon_pricing_research',
    name: 'Pricing Research',
    category: 'room',
    room: 'monetization',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'pricing_preview_band',
    description: 'Show the approximate center of the Perfect band before cursor starts moving.',
    mechanicNote: 'Improves manual pricing accuracy.',
  },
  {
    id: 'mon_annual_plans',
    name: 'Annual Plans',
    category: 'room',
    room: 'monetization',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'pricing_annual_cash_advance',
    description: 'Perfect pricing collects 75% of annualized ARR cohort immediately as Cash.',
    mechanicNote: 'Provides non-dilutive upfront liquidity for reinvestment.',
  },
  {
    id: 'mon_usage_metering',
    name: 'Usage Metering',
    category: 'room',
    room: 'monetization',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0.5,
    effectId: 'pricing_usage_metering',
    description: 'Underpriced deal yield improves from $12,500 to $18,750 ARR. Increases ops usage pressure.',
    mechanicNote: 'Higher ARR floor at the expense of infrastructure load.',
  },
  {
    id: 'mon_automation_license',
    name: 'Pricing Automation License',
    category: 'room',
    room: 'monetization',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'pricing_install_agent',
    description: 'Installs or upgrades the Pricing Agent line.',
    mechanicNote: 'Enables automatic pricing contract closure.',
  },
  {
    id: 'mon_enterprise_packaging',
    name: 'Enterprise Packaging',
    category: 'room',
    room: 'monetization',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'pricing_enterprise_packaging',
    description: 'Perfect zone width -40%, but Perfect result becomes +2.5 Growth Units. Too Expensive adds 0.10 Churn Threat.',
    mechanicNote: 'High skill, high payout pricing profile.',
  },

  // ==========================================
  // RETENTION (5)
  // ==========================================
  {
    id: 'ret_knowledge_base',
    name: 'Knowledge Base',
    category: 'room',
    room: 'retention',
    rarity: 'common',
    costCu: 1,
    complexity: 0.25,
    effectId: 'retention_auto_s1',
    description: 'Automatically destroys every second S1 informational threat.',
    mechanicNote: 'Reduces low-tier churn burden.',
  },
  {
    id: 'ret_billing_retry',
    name: 'Billing Retry',
    category: 'room',
    room: 'retention',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'retention_billing_retry',
    description: 'Failed-payment S1 threats automatically retry once after 2 seconds.',
    mechanicNote: 'Protects against payment churn spikes.',
  },
  {
    id: 'ret_root_cause_fix',
    name: 'Root Cause Fix',
    category: 'room',
    room: 'retention',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'retention_suppress_cause',
    description: 'Destroying three threats with same cause suppresses that cause for 20s.',
    mechanicNote: 'Reward for deliberate threat prioritization.',
  },
  {
    id: 'ret_automation_license',
    name: 'Support Automation License',
    category: 'room',
    room: 'retention',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'retention_install_agent',
    description: 'Installs or upgrades the Support Agent turret line.',
    mechanicNote: 'Adds autonomous defensive turrets.',
  },
  {
    id: 'ret_customer_health',
    name: 'Customer Health',
    category: 'room',
    room: 'retention',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'retention_early_threat_warning',
    description: 'All threats visible 3s earlier. Founder turret range +20%.',
    mechanicNote: 'Substantial reaction time advantage.',
  },

  // ==========================================
  // EXPANSION (5)
  // ==========================================
  {
    id: 'exp_crm_signals',
    name: 'CRM Signals',
    category: 'room',
    room: 'expansion',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'expansion_reveal_need',
    description: 'Reveal one additional account customer need.',
    mechanicNote: 'Reduces blind module packing.',
  },
  {
    id: 'exp_bundles',
    name: 'Bundles',
    category: 'room',
    room: 'expansion',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'expansion_bundle_modules',
    description: 'Two compatible 1x1 modules may be packed into one single grid cell.',
    mechanicNote: 'Increases grid packing density.',
  },
  {
    id: 'exp_seat_meter',
    name: 'Seat Meter',
    category: 'room',
    room: 'expansion',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0,
    effectId: 'expansion_seat_expansion',
    description: 'Accounts accept repeatable Seats module. Base Expansion cap +2 percentage points.',
    mechanicNote: 'Raises the maximum expansion ceiling.',
  },
  {
    id: 'exp_automation_license',
    name: 'Account Automation License',
    category: 'room',
    room: 'expansion',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'expansion_install_agent',
    description: 'Installs or upgrades the Account Agent line.',
    mechanicNote: 'Automates account module packing.',
  },
  {
    id: 'exp_partner_motion',
    name: 'Partner Motion',
    category: 'room',
    room: 'expansion',
    rarity: 'rare',
    costCu: 3,
    complexity: 0.5,
    effectId: 'expansion_partner_demand',
    description: 'Exceptional Expansion fits create one qualified Marketing card worth 0.5 Demand.',
    mechanicNote: 'Converts upsells into inbound demand.',
  },

  // ==========================================
  // OPERATIONS (5)
  // ==========================================
  {
    id: 'ops_cost_explorer',
    name: 'Cost Explorer',
    category: 'room',
    room: 'operations',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'ops_initial_reveal',
    description: 'Every Operations card begins 25% revealed.',
    mechanicNote: 'Requires fewer scratch gestures to reach diagnosis.',
  },
  {
    id: 'ops_observability',
    name: 'Observability',
    category: 'room',
    room: 'operations',
    rarity: 'common',
    costCu: 1,
    complexity: 0.25,
    effectId: 'ops_show_category',
    description: 'Incident category is visible before scratching begins.',
    mechanicNote: 'Immediate insight into incident severity and type.',
  },
  {
    id: 'ops_queueing',
    name: 'Queueing',
    category: 'room',
    room: 'operations',
    rarity: 'uncommon',
    costCu: 2,
    complexity: 0.5,
    effectId: 'room_operations_queueing',
    description: 'At Strain 1.00 to 1.25, agent reliability no longer drops. Excess work becomes visible backlog.',
    mechanicNote: 'Protects Strained organizations from reliability collapse.',
  },
  {
    id: 'ops_automation_license',
    name: 'Ops Automation License',
    category: 'room',
    room: 'operations',
    rarity: 'common',
    costCu: 1,
    complexity: 0,
    effectId: 'ops_install_agent',
    description: 'Installs or upgrades the Ops Agent line.',
    mechanicNote: 'Automates incident triage and resolution.',
  },
  {
    id: 'ops_orchestrator',
    name: 'Orchestrator',
    category: 'room',
    room: 'operations',
    rarity: 'rare',
    costCu: 3,
    complexity: 1.0,
    effectId: 'ops_expand_capacity',
    description: 'Ops Capacity +4.',
    mechanicNote: 'Crucial for supporting high-complexity agent swarms.',
  },

  // ==========================================
  // CROSS-ROOM SYSTEMS (12)
  // ==========================================
  {
    id: 'sys_plg',
    name: 'Product-Led Growth',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'sys_plg',
    description: 'Every third VERIFIED Product ship creates one Marketing card worth 0.5 Demand.',
    mechanicNote: 'Links shipping velocity to inbound demand.',
  },
  {
    id: 'sys_support_to_roadmap',
    name: 'Support to Roadmap',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'sys_support_to_roadmap',
    description: 'Resolve 3 Retention threats with same cause to create 1 prioritized Product request.',
    mechanicNote: 'Shipping that request suppresses the cause for the rest of the quarter.',
  },
  {
    id: 'sys_usage_signals',
    name: 'Usage Signals',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0.5,
    effectId: 'sys_usage_signals',
    description: 'Every 5 resolved Retention threats reveal 1 hidden need on next Expansion account.',
    mechanicNote: 'Turns defensive customer support into upsell intelligence.',
  },
  {
    id: 'sys_land_and_expand',
    name: 'Land and Expand',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'sys_land_and_expand',
    description: 'Every third Perfect Monetization guarantees one Expansion account within 15s.',
    mechanicNote: 'Bridges new customer pricing to expansion opportunities.',
  },
  {
    id: 'sys_customer_advocacy',
    name: 'Customer Advocacy',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'sys_customer_advocacy',
    description: 'Every second Exceptional Expansion fit creates +1 qualified Demand.',
    mechanicNote: 'Happy expanded accounts fuel organic marketing.',
  },
  {
    id: 'sys_auto_qa',
    name: 'Auto QA',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 1.0,
    effectId: 'sys_auto_qa',
    description: 'Early-deploy consequences route to Operations as S2 incidents. Resolving within 20s cancels churn threat.',
    mechanicNote: 'Mitigates early-shipping risk through fast operational diagnosis.',
  },
  {
    id: 'sys_finops_loop',
    name: 'FinOps Loop',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0.5,
    effectId: 'sys_finops_loop',
    description: 'Resolve runaway-agent Ops incident to permanently reduce room agent monthly cost by 10% (max 30%).',
    mechanicNote: 'Permanent cost reduction through operational discipline.',
  },
  {
    id: 'sys_data_warehouse',
    name: 'Data Warehouse',
    category: 'system',
    rarity: 'legendary',
    costCu: 5,
    complexity: 2.0,
    effectId: 'sys_data_warehouse',
    description: 'Marketing and Monetization Agents share outcome signals. Both gain +8 pp reliability (capped at 98%).',
    mechanicNote: 'Massive reliability boost for GTM automation.',
  },
  {
    id: 'sys_capacity_aware_gtm',
    name: 'Capacity-Aware GTM',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 1.0,
    effectId: 'sys_capacity_aware_gtm',
    description: 'Marketing Agents stop pursuing cards if Product backlog exceeds 80% capacity; resume below 50%.',
    mechanicNote: 'Prevents downstream bottlenecks and lost activation.',
  },
  {
    id: 'sys_smart_router',
    name: 'Smart Router',
    category: 'system',
    rarity: 'legendary',
    costCu: 5,
    complexity: 2.0,
    effectId: 'sys_smart_router',
    description: 'Idle automated capacity contributes 25% throughput to one adjacent overloaded room.',
    mechanicNote: 'Dynamic load-balancing across the company cycle.',
  },
  {
    id: 'sys_product_feedback_loop',
    name: 'Product Feedback Loop',
    category: 'system',
    rarity: 'rare',
    costCu: 3,
    complexity: 0,
    effectId: 'sys_product_feedback_loop',
    description: 'Failed Expansion fit creates tagged Product request. Shipping it removes identical conflict.',
    mechanicNote: 'Engineers solve customer packaging objections.',
  },
  {
    id: 'sys_autonomous_revenue_loop',
    name: 'Autonomous Revenue Loop',
    category: 'system',
    rarity: 'legendary',
    costCu: 5,
    complexity: 4.0,
    effectId: 'sys_autonomous_revenue_loop',
    description: 'Marketing routes directly to Product to Monetization automatically. Pipeline throughput +25% while Stable/Strained.',
    mechanicNote: 'The apex automation engine; auto-disables in Overloaded/Critical states.',
  },

  // ==========================================
  // CURSED UPGRADES (6)
  // ==========================================
  {
    id: 'cursed_ragebait',
    name: 'Ragebait',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_ragebait',
    description: 'Marketing output x2.5, but 35% of pursued demand is Low-Quality (+25% churn threat).',
    mechanicNote: 'Explosive early demand with brutal downstream retention pressure.',
  },
  {
    id: 'cursed_ship_on_red',
    name: 'Ship on Red',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_ship_on_red',
    description: 'Skip TEST automatically. Product throughput +50%. Every unverified ship creates +$12,500 Churn Threat and +$500/mo leak.',
    mechanicNote: 'Hyperspeed feature shipping with extreme technical debt.',
  },
  {
    id: 'cursed_dark_patterns',
    name: 'Dark Patterns',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_dark_patterns',
    description: 'Too Cheap and Too Expensive both give +1.0 ARR. Every third conversion adds +0.50 Churn Threat.',
    mechanicNote: 'Short-term conversion at the cost of long-term trust.',
  },
  {
    id: 'cursed_oversell_enterprise',
    name: 'Oversell Enterprise',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_oversell_enterprise',
    description: 'Expansion ARR output x2. Fit <= 0 creates +0.75 Churn Threat instead of +0.25.',
    mechanicNote: 'Aggressive upsell promises that can blow up accounts.',
  },
  {
    id: 'cursed_yolo_permissions',
    name: 'YOLO Permissions',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_yolo_permissions',
    description: 'All agent throughput x1.75. All agent Complexity x1.50. Wrong actions resolve immediately.',
    mechanicNote: 'Massive automation speed with severe organizational strain.',
  },
  {
    id: 'cursed_leveraged_growth',
    name: 'Leveraged Growth',
    category: 'cursed',
    rarity: 'cursed',
    costCu: 0,
    complexity: 0,
    effectId: 'cursed_leveraged_growth',
    description: 'LOC Limit x2. APR +8 pp. Bankruptcy grace countdown halved (20s -> 10s).',
    mechanicNote: 'Debt rocket with razor-thin margin for error.',
  },
];
